import type { Declaration, Problem, ScanResult } from './scan.js';

/** The machine-readable inventory, the shape `nss scan --json` prints and CI reads. */
export interface Manifest {
  version: 1;
  generatedBy: 'nss';
  namespaces: Array<{
    namespace: string;
    backend: Declaration['backend'];
    owner?: string;
    description?: string;
    ttl?: number;
    schemaVersion?: number;
    file: string;
    line: number;
    keys: Array<{ name: string; type: string; source: string }>;
  }>;
  problems: Problem[];
}

const BACKEND_LABEL: Record<Declaration['backend'], string> = {
  local: 'local',
  session: 'session',
  memory: 'memory',
};

function pad(text: string, width: number): string {
  return text + ' '.repeat(Math.max(0, width - text.length));
}

function plural(count: number, one: string, many = `${one}s`): string {
  return `${count} ${count === 1 ? one : many}`;
}

/** The human report: what is stored, who owns it, and anything that needs attention. */
export function formatReport(result: ScanResult): string {
  const { declarations, problems, filesScanned } = result;
  const lines: string[] = [];

  const files = new Set(declarations.map((d) => d.file)).size;
  lines.push(
    `namespaced-storage · ${plural(declarations.length, 'namespace')} across ` +
      `${plural(files, 'file')} · ${plural(filesScanned, 'file')} scanned`,
  );

  if (declarations.length > 0) {
    lines.push('');
    const columns = [
      declarations.map((d) => d.namespace),
      declarations.map((d) => BACKEND_LABEL[d.backend]),
      declarations.map((d) => d.owner ?? '—'),
      declarations.map((d) => d.file),
    ].map((column) => Math.max(...column.map((cell) => cell.length)));

    for (const declaration of declarations) {
      lines.push(
        '  ' +
          [
            pad(declaration.namespace, columns[0] ?? 0),
            pad(BACKEND_LABEL[declaration.backend], columns[1] ?? 0),
            pad(declaration.owner ?? '—', columns[2] ?? 0),
            pad(declaration.file, columns[3] ?? 0),
            declaration.keys.length === 0 ? 'untyped' : plural(declaration.keys.length, 'key'),
          ].join('  '),
      );
    }
  }

  for (const problem of problems) {
    lines.push('');
    lines.push(
      problem.kind === 'duplicate'
        ? `✖ duplicate namespace "${problem.namespace}" on ${problem.backend ?? '?'}Storage`
        : '✖ namespace is not a string literal, so it cannot be inventoried',
    );
    for (const site of problem.sites) lines.push(`    ${site}`);
  }

  if (problems.length > 0) {
    lines.push('');
    lines.push(`✖ ${plural(problems.length, 'problem')}`);
  }

  return lines.join('\n');
}

export function formatJson(result: ScanResult): string {
  const manifest: Manifest = {
    version: 1,
    generatedBy: 'nss',
    namespaces: result.declarations.map((declaration) => ({
      namespace: declaration.namespace,
      backend: declaration.backend,
      ...(declaration.owner === undefined ? {} : { owner: declaration.owner }),
      ...(declaration.description === undefined ? {} : { description: declaration.description }),
      ...(declaration.ttl === undefined ? {} : { ttl: declaration.ttl }),
      ...(declaration.version === undefined ? {} : { schemaVersion: declaration.version }),
      file: declaration.file,
      line: declaration.line,
      keys: declaration.keys.map((key) => ({ name: key.name, type: key.type, source: key.source })),
    })),
    problems: result.problems,
  };
  return JSON.stringify(manifest, null, 2);
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, '\\|');
}

/** The committed, reviewable answer to "what does this app store?". */
export function formatDocs(result: ScanResult): string {
  const lines = [
    '# Storage inventory',
    '',
    '<!-- Generated by `nss docs`. Do not edit by hand. -->',
    '',
  ];

  if (result.declarations.length === 0) {
    lines.push('No namespaces found.', '');
    return lines.join('\n');
  }

  lines.push(
    '| namespace | storage | owner | keys | description |',
    '| --------- | ------- | ----- | ---- | ----------- |',
  );

  for (const declaration of result.declarations) {
    const keys =
      declaration.keys.length === 0
        ? '—'
        : declaration.keys.map((key) => `\`${key.name}: ${key.type}\``).join(', ');
    lines.push(
      `| \`${declaration.namespace}\` | ${BACKEND_LABEL[declaration.backend]} | ` +
        `${declaration.owner ?? '—'} | ${escapePipes(keys)} | ` +
        `${escapePipes(declaration.description ?? '—')} |`,
    );
  }

  lines.push(
    '',
    `${result.declarations.length} namespaces · generated from source, never by hand.`,
    '',
  );
  return lines.join('\n');
}
